if(NOT DEFINED REMOTEDESK_SOURCE_ROOT OR
   NOT DEFINED REMOTEDESK_OUTPUT_FILE)
    message(FATAL_ERROR "RemoteDesktop build identity paths are required")
endif()

set(REMOTEDESK_GIT_SHORT_SHA "unknown")
execute_process(
    COMMAND git rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${REMOTEDESK_SOURCE_ROOT}"
    RESULT_VARIABLE REMOTEDESK_GIT_RESULT
    OUTPUT_VARIABLE REMOTEDESK_GIT_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(REMOTEDESK_GIT_RESULT EQUAL 0 AND
   REMOTEDESK_GIT_OUTPUT MATCHES "^[0-9a-fA-F]+$")
    set(REMOTEDESK_GIT_SHORT_SHA "${REMOTEDESK_GIT_OUTPUT}")
endif()
string(TIMESTAMP REMOTEDESK_BUILD_TIME_UTC "%Y-%m-%dT%H:%M:%SZ" UTC)

get_filename_component(REMOTEDESK_OUTPUT_DIR
    "${REMOTEDESK_OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${REMOTEDESK_OUTPUT_DIR}")
set(REMOTEDESK_TEMP_FILE "${REMOTEDESK_OUTPUT_FILE}.tmp")
file(WRITE "${REMOTEDESK_TEMP_FILE}"
    "#pragma once\n"
    "#define REMOTEDESK_GIT_SHORT_SHA \"${REMOTEDESK_GIT_SHORT_SHA}\"\n"
    "#define REMOTEDESK_BUILD_TIME_UTC \"${REMOTEDESK_BUILD_TIME_UTC}\"\n")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different
        "${REMOTEDESK_TEMP_FILE}" "${REMOTEDESK_OUTPUT_FILE}"
    RESULT_VARIABLE REMOTEDESK_COPY_RESULT
)
file(REMOVE "${REMOTEDESK_TEMP_FILE}")
if(NOT REMOTEDESK_COPY_RESULT EQUAL 0)
    message(FATAL_ERROR "Unable to write RemoteDesktop build identity header")
endif()
